wsl = false
no-multigrid = false
vsync = true
maximized = true
srgb = false
idle = false
neovim-bin = "/home/xia/Softwares/neovim/nvim" # in reality found dynamically on $PATH if unset
frame = "full"
