fork = false
frame = "full"
idle = false
maximized = false
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = true

[font]
size = 12.5
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Regular"
[[font.normal]]
family = "Microsoft YaHei UI"
style = "Regular"

[[font.Bold]]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[[font.Bold]]
family = "Microsoft YaHei UI"
style = "Bold"

